In [1]:
!git clone -b master https://github.com/charles9n/bert-sklearn
!cd bert-sklearn; pip install .

Cloning into 'bert-sklearn'...
remote: Enumerating objects: 259, done.
remote: Total 259 (delta 0), reused 0 (delta 0), pack-reused 259
Receiving objects: 100% (259/259), 516.15 KiB | 13.23 MiB/s, done.
Resolving deltas: 100% (131/131), done.
Processing /content/bert-sklearn
     |████████████████████████████████| 133kB 10.0MB/s 
     |████████████████████████████████| 7.5MB 9.7MB/s 
     |████████████████████████████████| 81kB 10.1MB/s 
  Created wheel for bert-sklearn: filename=bert_sklearn-0.3.1-cp37-none-any.whl size=54235 sha256=9470904c4f4fb41bef9ff64d0cfc5601a5970616a5565da15279b4e80e4bfd0c
  Stored in directory: /root/.cache/pip/wheels/61/95/c6/5790aae8fb377f5ff356dbe58205aab28858595d6bff8197d0
Successfully built bert-sklearn
ERROR: botocore 1.20.69 has requirement urllib3<1.27,>=1.25.4, but you'll have urllib3 1.24.3 which is incompatible.


In [8]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from bert_sklearn import BertClassifier

In [3]:
train_df = pd.read_csv('https://raw.githubusercontent.com/aatishsuman/health-advice/master/data/pubmed_causal_language_use.csv')
train_df = train_df.sample(frac=1, random_state=24).reset_index(drop=True)
train_df

sentence  label
0     A simultaneous integrated boost strategy could...      2
1     These may represent a precursor or forme frust...      2
2     Future studies should explore whether tailorin...      0
3     Critically ill patients with subarachnoid hemo...      3
4     Unique identifiers: NCT01507831, NCT01623115, ...      0
...                                                 ...    ...
3056  On the other hand, the decrease in leptin and ...      3
3057  Early detection and treatment of these two dis...      0
3058  Together with mean HbA1c, baseline urine album...      3
3059  The answer to that question should inform futu...      0
3060  Ophthalmic Surg Lasers Imaging Retina.2017;48:...      0

[3061 rows x 2 columns]

In [4]:
test_df = pd.read_csv('https://raw.githubusercontent.com/aatishsuman/health-advice/master/data/test.csv')
test_df

pmid  ... label
0    26261577  ...     1
1    26261577  ...     3
2    26261577  ...     0
3    26261577  ...     0
4    26261577  ...     0
..        ...  ...   ...
910  31473412  ...     3
911  31473412  ...     0
912  31473412  ...     3
913  31473412  ...     3
914  31473412  ...     0

[915 rows x 7 columns]

In [5]:
model = BertClassifier(random_state=42)
print(model)
model.fit(train_df['sentence'], train_df['label'])

Building sklearn text classifier...
BertClassifier(bert_config_json=None, bert_model='bert-base-uncased',
               bert_vocab=None, do_lower_case=None, epochs=3, eval_batch_size=8,
               fp16=False, from_tf=False, gradient_accumulation_steps=1,
               ignore_label=None, label_list=None, learning_rate=2e-05,
               local_rank=-1, logfile='bert_sklearn.log', loss_scale=0,
               max_seq_length=128, num_mlp_hiddens=500, num_mlp_layers=0,
               random_state=42, restore_file=None, train_batch_size=32,
               use_cuda=True, validation_fraction=0.1, warmup_proportion=0.1)


100%|██████████| 231508/231508 [00:00<00:00, 895465.41B/s]


Loading bert-base-uncased model...


100%|██████████| 433/433 [00:00<00:00, 87748.64B/s]


Defaulting to linear classifier/regressor
Loading Pytorch checkpoint

train data size: 2755, validation data size: 306



/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 5 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


/usr/local/lib/python3.7/dist-packages/bert_sklearn/model/pytorch_pretrained/optimization.py:275: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:1005.)
  next_m.mul_(beta1).add_(1 - beta1, grad)




Epoch 1, Train loss: 0.7544, Val loss: 0.3460, Val accy: 88.24%





Epoch 2, Train loss: 0.2184, Val loss: 0.3622, Val accy: 86.93%





Epoch 3, Train loss: 0.0772, Val loss: 0.3468, Val accy: 90.20%



BertClassifier(bert_config_json=None, bert_model='bert-base-uncased',
               bert_vocab=None, do_lower_case=True, epochs=3, eval_batch_size=8,
               fp16=False, from_tf=False, gradient_accumulation_steps=1,
               ignore_label=None, label_list=array([0, 1, 2, 3]),
               learning_rate=2e-05, local_rank=-1, logfile='bert_sklearn.log',
               loss_scale=0, max_seq_length=128, num_mlp_hiddens=500,
               num_mlp_layers=0, random_state=42, restore_file=None,
               train_batch_size=32, use_cuda=True, validation_fraction=0.1,
               warmup_proportion=0.1)

In [6]:
model = BertClassifier(bert_model='biobert-base-cased', random_state=42)
print(model)
model.fit(train_df['sentence'], train_df['label'])

Building sklearn text classifier...
BertClassifier(bert_config_json=None, bert_model='biobert-base-cased',
               bert_vocab=None, do_lower_case=None, epochs=3, eval_batch_size=8,
               fp16=False, from_tf=False, gradient_accumulation_steps=1,
               ignore_label=None, label_list=None, learning_rate=2e-05,
               local_rank=-1, logfile='bert_sklearn.log', loss_scale=0,
               max_seq_length=128, num_mlp_hiddens=500, num_mlp_layers=0,
               random_state=42, restore_file=None, train_batch_size=32,
               use_cuda=True, validation_fraction=0.1, warmup_proportion=0.1)


  0%|          | 0/401403346 [00:00<?, ?B/s]

Loading biobert-base-cased model...


100%|██████████| 401403346/401403346 [00:06<00:00, 59350317.20B/s]


Defaulting to linear classifier/regressor
Loading Tensorflow checkpoint from  model.ckpt-1000000

train data size: 2755, validation data size: 306



/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 5 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))




Epoch 1, Train loss: 0.7139, Val loss: 0.3019, Val accy: 90.52%





Epoch 2, Train loss: 0.2018, Val loss: 0.2496, Val accy: 91.18%





Epoch 3, Train loss: 0.0768, Val loss: 0.2532, Val accy: 92.16%



BertClassifier(bert_config_json=None, bert_model='biobert-base-cased',
               bert_vocab=None, do_lower_case=False, epochs=3,
               eval_batch_size=8, fp16=False, from_tf=False,
               gradient_accumulation_steps=1, ignore_label=None,
               label_list=array([0, 1, 2, 3]), learning_rate=2e-05,
               local_rank=-1, logfile='bert_sklearn.log', loss_scale=0,
               max_seq_length=128, num_mlp_hiddens=500, num_mlp_layers=0,
               random_state=42, restore_file=None, train_batch_size=32,
               use_cuda=True, validation_fraction=0.1, warmup_proportion=0.1)

In [13]:
train_pred = model.predict(train_df['sentence'])
print('Train classification report:\n', classification_report(train_df['label'], train_pred, target_names=['0','1','2','3']), '\n')

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 5 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))



Train classification report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.99      1356
           1       0.99      0.96      0.98       494
           2       0.94      0.97      0.96       213
           3       0.98      0.99      0.99       998

    accuracy                           0.98      3061
   macro avg       0.98      0.98      0.98      3061
weighted avg       0.98      0.98      0.98      3061
 



In [18]:
# Using all test data v1
print('Using all test data v1 - \n')

test_df['prediction'] = model.predict(test_df['sentence'])
print('Test classification report:\n', classification_report(test_df['label'], test_df['prediction'], target_names=['0','1','2','3']), '\n')
print('Confusion matrix -\n', confusion_matrix(test_df['label'], test_df['prediction'], labels=[0,1,2,3]))

error_df = test_df.query('label != prediction')
print('Total errors - ', error_df.shape[0], '\n')
print('Distribution of errors across type of study:\n', np.unique(error_df['design'], return_counts=True), '\n')
print('Distribution of type of relation across studies in test data:\n', pd.crosstab(test_df['design'], test_df['label']), '\n')
print('Distribution of type of relation across studies in errors:\n', pd.crosstab(error_df['design'], error_df['label']), '\n')

Using all test data v1



/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 5 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))



Test classification report:
               precision    recall  f1-score   support

           0       0.96      0.74      0.84       636
           1       0.44      0.85      0.58        61
           2       0.61      0.74      0.67        19
           3       0.62      0.88      0.73       199

    accuracy                           0.78       915
   macro avg       0.66      0.80      0.70       915
weighted avg       0.84      0.78      0.79       915
 

Confusion matrix -
 [[472  51   6 107]
 [  6  52   2   1]
 [  3   2  14   0]
 [ 10  13   1 175]]
Total errors -  202 

Distribution of errors across type of study:
 (array(['Case-Control Studies', 'Cross-Sectional Studies',
       'Prospective Studies', 'RCT', 'Retrospective Studies'],
      dtype=object), array([40, 41, 42, 47, 32])) 

Distribution of type of relation across studies in test data:
 label                      0   1  2   3
design                                 
Case-Control Studies      98  17  2  45
Cross-Secti

In [15]:
# actual - no relation, predicted - correlation
list(error_df.query('label == 0 & prediction == 3')['sentence'])

['In conclusion, this study indicated that the ARR act as the biomarker for the primary aldosteronism, and could distinguish from chronic kidney disease.',
 'Opioid requirement was different between the 2 groups on postoperative day (POD) 0 (12.4 vs 11.3\\u200amg of morphine-equivalent dose), but not from POD 1 to POD 4. ',
 'The diameter of the CS ostium in the superoinferior direction (1.13\\xa0±\\xa00.26\\xa0cm) was larger than in the anteroposterior direction (0.82\\xa0±\\xa00.19\\xa0cm) (P\\xa0<\\xa00.05). ',
 'Of the 13 patients who had a positive C. trachomatis antigen or nucleic acid test result, 9 had IgG and/or IgM titers highest against C. trachomatis, 3 had IgG titers highest against C. pneumoniae, and 1 had undetectable titers for the three chlamydial species. ',
 'This retrospective study investigated the correlation between liver tests abnormalities and treatment outcomes in patients with unresectable advanced or metastatic soft tissue sarcomas (STS) treated with trabect

In [16]:
# actual - no relation, predicted - causation
list(error_df.query('label == 0 & prediction == 1')['sentence'])

['In cardiac resynchronization therapy (CRT), left ventricular (LV) pacing is achieved by positioning the LV lead in one of the tributaries of the coronary sinus (CS). ',
 'Negative sputum culture conversion was achieved and maintained in all except two mortalities. ',
 'However, the impact of trabectedin-related transaminase elevations on treatment outcomes is unclear. ',
 'The effect of grade 3/4 elevations in alanine aminotransferase (ALT) or aspartate aminotransferase (AST) during the first two cycles and at any time during trabectedin treatment on progression-free survival (PFS) and overall survival (OS) were analyzed. ',
 'We sought to decrease DUP in rural Argentina by instituting annual training of local health agents to better identify signs of mental illness and offer earlier intervention. ',
 'This study aimed to determine if intraoperative remifentanil infusion caused increased pain during the postoperative period in patients who underwent a thyroidectomy. ',
 'Autologous s

In [38]:
# Using all test data v2
print('Using all test data v2 - \n')

test_df_v2 = pd.read_csv('https://raw.githubusercontent.com/aatishsuman/health-advice/master/data/test_v2.csv')

test_df_v2['prediction'] = model.predict(test_df_v2['sentence'])
print('Test classification report:\n', classification_report(test_df_v2['label'], test_df_v2['prediction'], target_names=['0','1','2','3']), '\n')
print('Confusion matrix -\n', confusion_matrix(test_df_v2['label'], test_df_v2['prediction'], labels=[0,1,2,3]))

error_df = test_df_v2.query('label != prediction')
print('Total errors - ', error_df.shape[0], '\n')
print('Distribution of errors across type of study:\n', np.unique(error_df['design'], return_counts=True), '\n')
print('Distribution of type of relation across studies in test data:\n', pd.crosstab(test_df_v2['design'], test_df_v2['label']), '\n')
print('Distribution of type of relation across studies in errors:\n', pd.crosstab(error_df['design'], error_df['label']), '\n')

Using all test data v2 - 



/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 5 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))



Test classification report:
               precision    recall  f1-score   support

           0       0.96      0.79      0.87       597
           1       0.49      0.87      0.63        67
           2       0.61      0.74      0.67        19
           3       0.73      0.89      0.80       232

    accuracy                           0.82       915
   macro avg       0.70      0.82      0.74       915
weighted avg       0.86      0.82      0.83       915
 

Confusion matrix -
 [[472  43   6  76]
 [  6  58   2   1]
 [  3   2  14   0]
 [ 10  15   1 206]]
Total errors -  165 

Distribution of errors across type of study:
 (array(['Case-Control Studies', 'Cross-Sectional Studies',
       'Prospective Studies', 'RCT', 'Retrospective Studies'],
      dtype=object), array([34, 37, 36, 32, 26])) 

Distribution of type of relation across studies in test data:
 label                      0   1  2   3
design                                 
Case-Control Studies      92  19  2  49
Cross-Secti

In [39]:
# Using bottom half of articles for test data v2
print('Using bottom half for test data v2 - \n')

filtered_test_df = test_df_v2.query('location > count/2')
filtered_test_df['prediction'] = model.predict(filtered_test_df['sentence'])
print('Test classification report:\n', classification_report(filtered_test_df['label'], filtered_test_df['prediction'], target_names=['0','1','2','3']), '\n')
print('Confusion matrix -\n', confusion_matrix(filtered_test_df['label'], filtered_test_df['prediction'], labels=[0,1,2,3]))

error_df = filtered_test_df.query('label != prediction')
print('Total errors - ', error_df.shape[0], '\n')
print('Distribution of errors across type of study:\n', np.unique(error_df['design'], return_counts=True), '\n')
print('Distribution of type of relation across studies in test data:\n', pd.crosstab(filtered_test_df['design'], filtered_test_df['label']), '\n')
print('Distribution of type of relation across studies in errors:\n', pd.crosstab(error_df['design'], error_df['label']), '\n')

Using bottom half for test data v2 - 



/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 5 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))



Test classification report:
               precision    recall  f1-score   support

           0       0.93      0.85      0.89       213
           1       0.62      0.87      0.73        47
           2       0.69      0.73      0.71        15
           3       0.90      0.90      0.90       194

    accuracy                           0.87       469
   macro avg       0.79      0.84      0.81       469
weighted avg       0.88      0.87      0.87       469
 

Confusion matrix -
 [[180  13   2  18]
 [  3  41   2   1]
 [  3   1  11   0]
 [  7  11   1 175]]
Total errors -  62 

Distribution of errors across type of study:
 (array(['Case-Control Studies', 'Cross-Sectional Studies',
       'Prospective Studies', 'RCT', 'Retrospective Studies'],
      dtype=object), array([10, 17, 14, 11, 10])) 

Distribution of type of relation across studies in test data:
 label                     0   1  2   3
design                                
Case-Control Studies     27  11  2  41
Cross-Sectional

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [40]:
# actual - no relation, predicted - correlation
list(error_df.query('label == 0 & prediction == 3')['sentence'])

['Of the 13 patients who had a positive C. trachomatis antigen or nucleic acid test result, 9 had IgG and/or IgM titers highest against C. trachomatis, 3 had IgG titers highest against C. pneumoniae, and 1 had undetectable titers for the three chlamydial species. ',
 'Pain treatment increased progressively in complexity. ',
 'We found that, regardless of treatment, bone metastases appeared in a certain number of patients and that after excluding patients with prostate cancer a bone metastasis was the first sign of "recurrence" in 1.3% of the patients with a known primary solid malignant tumour.',
 'Serum levels of leukocyte differential counts, C-reactive protein (CRP), and neutrophil to lymphocyte ratio (NLR) were compared between women with no placental inflammation and women with PIR. ',
 'Sixteen had a past history of fractures (chi(2) = 10.7, p = 0.0004, v controls), which were of typical osteoporotic type. ',
 'Maximum voluntary ventilation, the ratio between forced expiratory vo

In [41]:
# actual - no relation, predicted - causation
list(error_df.query('label == 0 & prediction == 1')['sentence'])

['Negative sputum culture conversion was achieved and maintained in all except two mortalities. ',
 'The effect of grade 3/4 elevations in alanine aminotransferase (ALT) or aspartate aminotransferase (AST) during the first two cycles and at any time during trabectedin treatment on progression-free survival (PFS) and overall survival (OS) were analyzed. ',
 'ANP is known to bind specifically to NPR1 [also called guanylyl cyclase-A (GC-A) receptor]. ',
 'We examined the effect of ANP on tumor metastasis in mice treated with lipopolysaccharide, which mimics systemic inflammation induced by surgical stress. ',
 'There was inconsistent evidence supporting a sustained first-grade treatment effect: Individualized instruction in first grade was necessary but not sufficient for stronger third-grade reading outcomes. ',
 'Ventral stabilisation yields more advantages than dorsal instrumentation in the long term. ',
 'Thirty (56.6%) patients tolerated an early oral diet well within 24 h postoperat

In [42]:
# actual - correlation, predicted - causation
list(error_df.query('label == 3 & prediction == 1')['sentence'])

['Aprotinin was significantly more efficient than epsilon-aminocaproic acid (p=0.002). ',
 'Tranexamic acid did not have a statistically significant effect on blood loss. ',
 'The effect of the intervention was significantly larger in patients who were younger (interaction P\\xa0=\\xa0.02), did not have diabetes (P\\xa0=\\xa0.005), had high baseline diastolic BP (P\\xa0=\\xa0.02), added salt less than daily in food preparation (P\\xa0=\\xa0.007), and took 0-2 (rather than 3-6) antihypertensive medication classes at baseline (P\\xa0=\\xa0.02). ',
 'Analyses of covariance did not reveal significant treatment effects for memory (Buschke immediate recall, p\\u2009=\\u20090.53; delayed recall, p\\u2009=\\u20090.94), attention (Trails A speed, p\\u2009=\\u20090.81 and errors, p\\u2009=\\u20090.22; Digit Span Forward length, p\\u2009=\\u20090.66), executive functioning (Trails B speed, p\\u2009=\\u20090.97 and errors, p\\u2009=\\u20090.93; Digit Span Backward length, p\\u2009=\\u20090.60), la

In [43]:
# actual - conditional causation
list(error_df.query('label == 2')['sentence'])

['Our analysis suggests that the ST410 lineage should be classified with the potential to cause new high-risk clones. ',
 'Effective disease treatments may be heralded by normalizing trends of these noninvasive cardiovascular measures. ',
 'However, these associations, except for metabolic syndrome, were at least partly mediated by body mass index. ',
 'Closer links between health and development agendas could address these consequences of poverty and streamline access to adequate healthcare.']