In [1]:
!git clone -b master https://github.com/charles9n/bert-sklearn
!cd bert-sklearn; pip install .

Cloning into 'bert-sklearn'...
remote: Enumerating objects: 259, done.
remote: Total 259 (delta 0), reused 0 (delta 0), pack-reused 259
Receiving objects: 100% (259/259), 516.15 KiB | 1.58 MiB/s, done.
Resolving deltas: 100% (131/131), done.
Processing /content/bert-sklearn
     |████████████████████████████████| 133kB 7.5MB/s 
     |████████████████████████████████| 81kB 6.9MB/s 
     |████████████████████████████████| 7.5MB 11.3MB/s 
  Created wheel for bert-sklearn: filename=bert_sklearn-0.3.1-cp37-none-any.whl size=54235 sha256=bf22b865deb364421852f80b58118aec43f92db00573f321eeb7aa73271d1e33
  Stored in directory: /root/.cache/pip/wheels/61/95/c6/5790aae8fb377f5ff356dbe58205aab28858595d6bff8197d0
Successfully built bert-sklearn
ERROR: botocore 1.20.67 has requirement urllib3<1.27,>=1.25.4, but you'll have urllib3 1.24.3 which is incompatible.


In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from bert_sklearn import BertClassifier

In [3]:
train_df = pd.read_csv('https://raw.githubusercontent.com/aatishsuman/health-advice/master/data/pubmed_causal_language_use.csv')
train_df = train_df.sample(frac=1, random_state=24).reset_index(drop=True)
train_df

sentence  label
0     A simultaneous integrated boost strategy could...      2
1     These may represent a precursor or forme frust...      2
2     Future studies should explore whether tailorin...      0
3     Critically ill patients with subarachnoid hemo...      3
4     Unique identifiers: NCT01507831, NCT01623115, ...      0
...                                                 ...    ...
3056  On the other hand, the decrease in leptin and ...      3
3057  Early detection and treatment of these two dis...      0
3058  Together with mean HbA1c, baseline urine album...      3
3059  The answer to that question should inform futu...      0
3060  Ophthalmic Surg Lasers Imaging Retina.2017;48:...      0

[3061 rows x 2 columns]

In [4]:
test_df = pd.read_csv('https://raw.githubusercontent.com/aatishsuman/health-advice/master/data/test.csv')
test_df

pmid  ... label
0    26261577  ...     1
1    26261577  ...     3
2    26261577  ...     0
3    26261577  ...     0
4    26261577  ...     0
..        ...  ...   ...
910  31473412  ...     3
911  31473412  ...     0
912  31473412  ...     3
913  31473412  ...     3
914  31473412  ...     0

[915 rows x 7 columns]

In [5]:
model = BertClassifier(random_state=42)
print(model)
model.fit(train_df['sentence'], train_df['label'])

Building sklearn text classifier...
BertClassifier(bert_config_json=None, bert_model='bert-base-uncased',
               bert_vocab=None, do_lower_case=None, epochs=3, eval_batch_size=8,
               fp16=False, from_tf=False, gradient_accumulation_steps=1,
               ignore_label=None, label_list=None, learning_rate=2e-05,
               local_rank=-1, logfile='bert_sklearn.log', loss_scale=0,
               max_seq_length=128, num_mlp_hiddens=500, num_mlp_layers=0,
               random_state=42, restore_file=None, train_batch_size=32,
               use_cuda=True, validation_fraction=0.1, warmup_proportion=0.1)


100%|██████████| 231508/231508 [00:00<00:00, 868946.71B/s]


Loading bert-base-uncased model...


100%|██████████| 433/433 [00:00<00:00, 107808.00B/s]


Defaulting to linear classifier/regressor
Loading Pytorch checkpoint

train data size: 2755, validation data size: 306



/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 5 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


/usr/local/lib/python3.7/dist-packages/bert_sklearn/model/pytorch_pretrained/optimization.py:275: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:1005.)
  next_m.mul_(beta1).add_(1 - beta1, grad)




Epoch 1, Train loss: 0.7544, Val loss: 0.3460, Val accy: 88.24%





Epoch 2, Train loss: 0.2184, Val loss: 0.3622, Val accy: 86.93%





Epoch 3, Train loss: 0.0772, Val loss: 0.3468, Val accy: 90.20%



BertClassifier(bert_config_json=None, bert_model='bert-base-uncased',
               bert_vocab=None, do_lower_case=True, epochs=3, eval_batch_size=8,
               fp16=False, from_tf=False, gradient_accumulation_steps=1,
               ignore_label=None, label_list=array([0, 1, 2, 3]),
               learning_rate=2e-05, local_rank=-1, logfile='bert_sklearn.log',
               loss_scale=0, max_seq_length=128, num_mlp_hiddens=500,
               num_mlp_layers=0, random_state=42, restore_file=None,
               train_batch_size=32, use_cuda=True, validation_fraction=0.1,
               warmup_proportion=0.1)

In [6]:
model = BertClassifier(bert_model='biobert-base-cased', random_state=42)
print(model)
model.fit(train_df['sentence'], train_df['label'])

Building sklearn text classifier...
BertClassifier(bert_config_json=None, bert_model='biobert-base-cased',
               bert_vocab=None, do_lower_case=None, epochs=3, eval_batch_size=8,
               fp16=False, from_tf=False, gradient_accumulation_steps=1,
               ignore_label=None, label_list=None, learning_rate=2e-05,
               local_rank=-1, logfile='bert_sklearn.log', loss_scale=0,
               max_seq_length=128, num_mlp_hiddens=500, num_mlp_layers=0,
               random_state=42, restore_file=None, train_batch_size=32,
               use_cuda=True, validation_fraction=0.1, warmup_proportion=0.1)


  0%|          | 0/401403346 [00:00<?, ?B/s]

Loading biobert-base-cased model...


100%|██████████| 401403346/401403346 [00:06<00:00, 59076664.28B/s]


Defaulting to linear classifier/regressor
Loading Tensorflow checkpoint from  model.ckpt-1000000

train data size: 2755, validation data size: 306



/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 5 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))




Epoch 1, Train loss: 0.7139, Val loss: 0.3019, Val accy: 90.52%





Epoch 2, Train loss: 0.2018, Val loss: 0.2496, Val accy: 91.18%





Epoch 3, Train loss: 0.0768, Val loss: 0.2532, Val accy: 92.16%



BertClassifier(bert_config_json=None, bert_model='biobert-base-cased',
               bert_vocab=None, do_lower_case=False, epochs=3,
               eval_batch_size=8, fp16=False, from_tf=False,
               gradient_accumulation_steps=1, ignore_label=None,
               label_list=array([0, 1, 2, 3]), learning_rate=2e-05,
               local_rank=-1, logfile='bert_sklearn.log', loss_scale=0,
               max_seq_length=128, num_mlp_hiddens=500, num_mlp_layers=0,
               random_state=42, restore_file=None, train_batch_size=32,
               use_cuda=True, validation_fraction=0.1, warmup_proportion=0.1)

In [7]:
train_pred = model.predict(train_df['sentence'])
print('Train classification report:\n', classification_report(train_df['label'], train_pred, target_names=['0','1','2','3']), '\n')

test_pred = model.predict(test_df['sentence'])
print('Test classification report:\n', classification_report(test_df['label'], test_pred, target_names=['0','1','2','3']), '\n')

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 5 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))



Train classification report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.99      1356
           1       0.99      0.96      0.98       494
           2       0.94      0.97      0.96       213
           3       0.98      0.99      0.99       998

    accuracy                           0.98      3061
   macro avg       0.98      0.98      0.98      3061
weighted avg       0.98      0.98      0.98      3061
 




Test classification report:
               precision    recall  f1-score   support

           0       0.96      0.74      0.84       636
           1       0.44      0.85      0.58        61
           2       0.61      0.74      0.67        19
           3       0.62      0.88      0.73       199

    accuracy                           0.78       915
   macro avg       0.66      0.80      0.70       915
weighted avg       0.84      0.78      0.79       915
 



In [13]:
test_df['prediction'] = test_pred
print('Confusion matrix -\n', confusion_matrix(test_df['label'], test_df['prediction'], labels=[0,1,2,3]))

error_df = test_df.query('label != prediction')
print('Total errors - ', error_df.shape[0], '\n')
print('Distribution of errors across type of study:\n', np.unique(error_df['design'], return_counts=True), '\n')
print('Distribution of type of relation across studies in test data:\n', pd.crosstab(test_df['design'], test_df['label']), '\n')
print('Distribution of type of relation across studies in errors:\n', pd.crosstab(error_df['design'], error_df['label']), '\n')

Confusion matrix -
 [[472  51   6 107]
 [  6  52   2   1]
 [  3   2  14   0]
 [ 10  13   1 175]]
Total errors -  202 

Distribution of errors across type of study:
 (array(['Case-Control Studies', 'Cross-Sectional Studies',
       'Prospective Studies', 'RCT', 'Retrospective Studies'],
      dtype=object), array([40, 41, 42, 47, 32])) 

Distribution of type of relation across studies in test data:
 label                      0   1  2   3
design                                 
Case-Control Studies      98  17  2  45
Cross-Sectional Studies  141  10  5  55
Prospective Studies      125  12  9  38
RCT                      136  11  1  30
Retrospective Studies    136  11  2  31 

Distribution of type of relation across studies in errors:
 label                     0  1  2  3
design                              
Case-Control Studies     35  2  0  3
Cross-Sectional Studies  29  2  2  8
Prospective Studies      31  3  3  5
RCT                      39  2  0  6
Retrospective Studies    30  0  0 

In [9]:
# actual - no relation, predicted - correlation
list(error_df.query('label == 0 & prediction == 3')['sentence'])

['In conclusion, this study indicated that the ARR act as the biomarker for the primary aldosteronism, and could distinguish from chronic kidney disease.',
 'Opioid requirement was different between the 2 groups on postoperative day (POD) 0 (12.4 vs 11.3\\u200amg of morphine-equivalent dose), but not from POD 1 to POD 4. ',
 'The diameter of the CS ostium in the superoinferior direction (1.13\\xa0±\\xa00.26\\xa0cm) was larger than in the anteroposterior direction (0.82\\xa0±\\xa00.19\\xa0cm) (P\\xa0<\\xa00.05). ',
 'Of the 13 patients who had a positive C. trachomatis antigen or nucleic acid test result, 9 had IgG and/or IgM titers highest against C. trachomatis, 3 had IgG titers highest against C. pneumoniae, and 1 had undetectable titers for the three chlamydial species. ',
 'This retrospective study investigated the correlation between liver tests abnormalities and treatment outcomes in patients with unresectable advanced or metastatic soft tissue sarcomas (STS) treated with trabect

In [10]:
# actual - no relation, predicted - causation
list(error_df.query('label == 0 & prediction == 1')['sentence'])

['In cardiac resynchronization therapy (CRT), left ventricular (LV) pacing is achieved by positioning the LV lead in one of the tributaries of the coronary sinus (CS). ',
 'Negative sputum culture conversion was achieved and maintained in all except two mortalities. ',
 'However, the impact of trabectedin-related transaminase elevations on treatment outcomes is unclear. ',
 'The effect of grade 3/4 elevations in alanine aminotransferase (ALT) or aspartate aminotransferase (AST) during the first two cycles and at any time during trabectedin treatment on progression-free survival (PFS) and overall survival (OS) were analyzed. ',
 'We sought to decrease DUP in rural Argentina by instituting annual training of local health agents to better identify signs of mental illness and offer earlier intervention. ',
 'This study aimed to determine if intraoperative remifentanil infusion caused increased pain during the postoperative period in patients who underwent a thyroidectomy. ',
 'Autologous s